title: Postman Schema
description: >-
  This schema contains a full definition of your API, including it's data types, security requirements,
  resources, methods, and even deprecation information.
type: object
required:
  - resources
properties:
  resources:
    $ref: "#/definitions/Resources"
  security:
    $ref: "#/definitions/Security"
  definitions:
    $ref: "#/definitions/JsonSchema/definitions/JsonSchemaMap"

patternProperties:
  "^_":
    $ref: ../types.yaml#/definitions/AnyType
additionalProperties: false

definitions:
  Resources:
    type: array
    minItems: 0
    items:
      $ref: "#/definitions/Resource"

  Resource:
    $ref: resource.yaml

  RequestSchema:
    $ref: request-schema.yaml

  ResponseSchema:
    $ref: response-schema.yaml

  Security:
    $ref: security.yaml

  JsonSchema:
    $ref: json-schema.yaml
