title: XXXXXXXXXXX
description: XXXXXXXXXXX
type: object
required:
  - XXXXXXXXXXX
  - XXXXXXXXXXX
properties:
  XXXXXXXXXXX:
    type: XXXXXXXXXXX
patternProperties:
  "^_":
    $ref: json-schema.yaml#/definitions/AnyType
additionalProperties: false
